//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3DS_CivilSurveySuite.ACAD2017 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3DS_CivilSurveySuite.ACAD2017.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Accept position?.
        /// </summary>
        public static string Accept_Position {
            get {
                return ResourceManager.GetString("Accept_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Offset distance:.
        /// </summary>
        public static string Offset_Distance {
            get {
                return ResourceManager.GetString("Offset_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Pick offset side:.
        /// </summary>
        public static string Pick_Offset_Side {
            get {
                return ResourceManager.GetString("Pick_Offset_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Select first line or polyline:.
        /// </summary>
        public static string Select_First_Line_Or_Polyline {
            get {
                return ResourceManager.GetString("Select_First_Line_Or_Polyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Select line or polyline:.
        /// </summary>
        public static string Select_Line_Or_Polyline {
            get {
                return ResourceManager.GetString("Select_Line_Or_Polyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Select second line or polyline:.
        /// </summary>
        public static string Select_Second_Line_Or_Polyline {
            get {
                return ResourceManager.GetString("Select_Second_Line_Or_Polyline", resourceCulture);
            }
        }
    }
}
