//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3DS_CivilSurveySuite.UI.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3DS_CivilSurveySuite.UI.Strings.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Accept position?.
        /// </summary>
        internal static string ACAD_AcceptPosition {
            get {
                return ResourceManager.GetString("ACAD_AcceptPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Loading Civil Survey Suite for AutoCAD....
        /// </summary>
        internal static string ACAD_Loading {
            get {
                return ResourceManager.GetString("ACAD_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Error Loading Civil Survey Suite for AutoCAD:.
        /// </summary>
        internal static string ACAD_LoadingError {
            get {
                return ResourceManager.GetString("ACAD_LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Offset distance:.
        /// </summary>
        internal static string ACAD_OffsetDistance {
            get {
                return ResourceManager.GetString("ACAD_OffsetDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Pick offset side:.
        /// </summary>
        internal static string ACAD_PickOffsetSide {
            get {
                return ResourceManager.GetString("ACAD_PickOffsetSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Select first line or polyline:.
        /// </summary>
        internal static string ACAD_SelectFirstLineOrPolyline {
            get {
                return ResourceManager.GetString("ACAD_SelectFirstLineOrPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Select line or polyline:.
        /// </summary>
        internal static string ACAD_SelectLineOrPolyline {
            get {
                return ResourceManager.GetString("ACAD_SelectLineOrPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Select second line or polyline:.
        /// </summary>
        internal static string ACAD_SelectSecondLineOrPolyline {
            get {
                return ResourceManager.GetString("ACAD_SelectSecondLineOrPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Loading Civil Survey Suite for Civil 3D....
        /// </summary>
        internal static string C3D_Loading {
            get {
                return ResourceManager.GetString("C3D_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS&gt; Error Loading Civil Survey Suite for Civil 3D:.
        /// </summary>
        internal static string C3D_LoadingError {
            get {
                return ResourceManager.GetString("C3D_LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut/Fill.
        /// </summary>
        internal static string CutFill {
            get {
                return ResourceManager.GetString("CutFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easting.
        /// </summary>
        internal static string Easting {
            get {
                return ResourceManager.GetString("Easting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation.
        /// </summary>
        internal static string Elevation {
            get {
                return ResourceManager.GetString("Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Description.
        /// </summary>
        internal static string FullDescription {
            get {
                return ResourceManager.GetString("FullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northing.
        /// </summary>
        internal static string Northing {
            get {
                return ResourceManager.GetString("Northing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Number.
        /// </summary>
        internal static string PointNumber {
            get {
                return ResourceManager.GetString("PointNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Description.
        /// </summary>
        internal static string RawDescription {
            get {
                return ResourceManager.GetString("RawDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        internal static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
    }
}
